---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: roboshop
data:
  CART_HOST: "cart:80"
  USER_HOST: "user"
  AMQP_HOST: "rabbitmq"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: roboshop
  labels:
    tier: app
    name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      name: payment
  template:
    metadata:
      labels:
        tier: app
        name: payment
    spec:
      containers:
      - name: payment
        imagePullPolicy: Always
        image: kiranprav/payment:v1
        envFrom:
        - configMapRef:
            name: payment-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    tier: app
    name: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080




