---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: roboshop
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: roboshop
  labels:
    tier: app
    name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      name: cart
  template:
    metadata:
      labels:
        tier: app
        name: cart
    spec:
      containers:
      - name: cart
        imagePullPolicy: Always
        image: kiranprav/cart:v1
        envFrom:
        - configMapRef:
            name: cart-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    tier: app
    name: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080




