---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  namespace: roboshop
  labels:
    tier: app
    name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      name: shipping
  template:
    metadata:
      labels:
        tier: app
        name: shipping
    spec:
      containers:
      - name: shipping
        imagePullPolicy: Always
        image: kiranprav/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    tier: app
    name: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080




