apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb # has to match .spec.selector.matchLabels
    tier: db
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None # this is called as headless service
  selector:
    name: mongodb # has to match .spec.selector.matchLabels
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      name: mongodb # has to match .spec.selector.matchLabels
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        name: mongodb # has to match .spec.selector.matchLabels
        tier: db
    spec:
      containers:
      - name: mogndb
        imagePullPolicy: Always
        image: kiranprav/mongo:v1
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 1Gi


