
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None #headless service
  selector:
    name: redis
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      name: redis # has to match .spec.template.metadata.labels
      tier: db
  serviceName: "redis"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        name: redis # has to match .spec.template.metadata.labels
        tier: db
    spec:
      containers:
      - name: redis
        image: kiranprav/redis:v1
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi