apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: roboshop
data:
  nginx.conf: |
  
    # this config is loading from nginx config map
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    error_log  /var/log/nginx/error.log notice;

    events {
      worker_connections 768;
      # multi_accept on;
    }

    http {

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr $time_local $request $status $body_bytes_sent $request_time';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            location /api/catalogue/ {
              proxy_pass http://catalogue/;
            }

            location /api/user/ {
              proxy_pass http://user/;
            }

            location /api/cart/ {
              proxy_pass http://cart/;
            }

            location /api/shipping/ {
              proxy_pass http://shipping/;
            }

            location /api/payment/ {
              proxy_pass http://payment/;
            }

            proxy_http_version 1.1;
            location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.jpg;
            }

            location /nginx_status {
                stub_status on;
                access_log off;
            }
        }

    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: roboshop
  labels:
    tier: web
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: web
      name: frontend
  template:
    metadata:
      labels:
        tier: web
        name: frontend
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: kiranprav/web:v1
        resources:
          requests:
            cpu: "150m"
            memory: "250Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true  
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    tier: web
    name: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
